alias ll='ls -alF'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -iv'
alias vi='vim'
alias ex='vim'
alias pstree='pstree -Ap'
alias gcd='cd "$(git rev-parse --show-toplevel)"'
alias gs='git status -sb'
alias ga='git add'
alias gc='git commit'
alias gca='git commit --amend'
alias gco='git checkout'
alias gb='git branch'
alias gd='git diff'
alias gl='git log --oneline --decorate --graph -20'

alias k='kubectl'
alias kgp='kubectl get pods'
alias kgs='kubectl get svc'
alias kgn='kubectl get nodes'
alias kns='kubens'
alias kctx='kubectx'

alias py='python3'
alias uvr='uv run'
